# Generated by Django 5.1.7 on 2025-03-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('task_description', models.TextField(max_length=350)),
                ('category', models.CharField(choices=[('Important', 'Important'), ('Not important', 'not important')], default='Not important', max_length=20)),
            ],
        ),
    ]
